---
wifi_common_iface:
  ssid: "{{ vault_wifi_ssid }}"
  key: "{{ vault_wifi_password }}"
  encryption: psk2
  country: "{{ wifi_country | default('US') }}"
  network: 'lan'
  mode: 'ap'
  type: 'mac80211'
  cell_density: '0'
  disabled: '0'
  ft_over_ds: '0'
  ft_psk_generate_local: '1'
  ieee80211r: '1'
  bss_transition: '1'
  wnm_sleep_mode: '1'
  time_advertisement: '2'
  time_zone: "{{ timezone_zonename }}"
  ieee80211k: '1'
  mobility_domain: abcd
  wmm: '1'
